// AUTO-GENERATED by scripts/build-image-manifest.mjs — do not edit by hand.
// Re-run the script whenever files in public/images/ change.

export const IMAGES = {
  "brand-partners": [],
  "canopies": [
    "/images/canopies/CIMG3544-768x576-1.jpg",
    "/images/canopies/DSCN1091-768x576-1.jpg",
    "/images/canopies/gz1.jpg",
    "/images/canopies/gz2.jpg"
  ],
  "carports": [
    "/images/carports/CARPORTS-1-1.jpg",
    "/images/carports/CARPORTS-1-scaled.jpg",
    "/images/carports/CARPORTS-2-scaled.jpg",
    "/images/carports/CARPORTS-3.jpg",
    "/images/carports/CARPORTS-4.jpg",
    "/images/carports/CARPORTS-5-scaled.jpg"
  ],
  "extruded-aluminum": [
    "/images/extruded-aluminum/1-1-scaled.jpg",
    "/images/extruded-aluminum/2-1-scaled.jpg",
    "/images/extruded-aluminum/3-1-scaled.jpg",
    "/images/extruded-aluminum/4-1-scaled.jpg",
    "/images/extruded-aluminum/5-scaled.jpg",
    "/images/extruded-aluminum/6-1-scaled.jpg",
    "/images/extruded-aluminum/Extruded-canopy-and-louvers.jpg",
    "/images/extruded-aluminum/Extruded-canopy..jpg",
    "/images/extruded-aluminum/Roll-Form-canopyy.jpg"
  ],
  "fabric-awnings": [
    "/images/fabric-awnings/Fabric-awnings-10.jpg",
    "/images/fabric-awnings/Fabric-awnings-2.jpg",
    "/images/fabric-awnings/Fabric-awnings-3.jpg",
    "/images/fabric-awnings/Fabric-awnings-4.jpg",
    "/images/fabric-awnings/Fabric-awnings-5.jpg",
    "/images/fabric-awnings/Fabric-awnings-6.jpg",
    "/images/fabric-awnings/Fabric-awnings-7.jpg",
    "/images/fabric-awnings/Fabric-awnings-8.jpg",
    "/images/fabric-awnings/Fabric-awnings-9.jpg",
    "/images/fabric-awnings/unnamed.jpg"
  ],
  "gallery": [],
  "gazebos-cabanas": [
    "/images/gazebos-cabanas/CIMG3544-768x576-1.jpg",
    "/images/gazebos-cabanas/DSCN1091-768x576-1.jpg",
    "/images/gazebos-cabanas/blue-canopies.jpg",
    "/images/gazebos-cabanas/cc1-300x225-1.jpg",
    "/images/gazebos-cabanas/gazebos-2.png",
    "/images/gazebos-cabanas/gz1.jpg",
    "/images/gazebos-cabanas/gz2.jpg",
    "/images/gazebos-cabanas/gz3.jpg"
  ],
  "hero": [
    "/images/hero/Prompting_Runway_for_Subtle_Animation.mp4"
  ],
  "locations": [],
  "logo": [
    "/images/logo/aaa-awning-co-inc.png"
  ],
  "metal-awnings": [
    "/images/metal-awnings/m1.jpg",
    "/images/metal-awnings/m3.jpg",
    "/images/metal-awnings/m4.jpg",
    "/images/metal-awnings/m5.jpg",
    "/images/metal-awnings/metal-awning-1.jpg",
    "/images/metal-awnings/metal-awning-10.jpg",
    "/images/metal-awnings/metal-awning-2.jpg",
    "/images/metal-awnings/metal-awning-3-scaled.jpg",
    "/images/metal-awnings/metal-awning-4.jpg",
    "/images/metal-awnings/metal-awning-5-scaled.jpg",
    "/images/metal-awnings/metal-awning-6-scaled.jpg",
    "/images/metal-awnings/metal-awning-7.jpg",
    "/images/metal-awnings/metal-awning-8.jpg",
    "/images/metal-awnings/metal-awning-9.jpg"
  ],
  "motorized-screens": [],
  "patio-curtains": [
    "/images/patio-curtains/Curtains-1.jpg",
    "/images/patio-curtains/Curtains-2-scaled.jpg",
    "/images/patio-curtains/Curtains-3-scaled-e1619539405515.jpg",
    "/images/patio-curtains/Curtains-4.jpg",
    "/images/patio-curtains/Curtains-5.jpg",
    "/images/patio-curtains/Curtains-6.jpg",
    "/images/patio-curtains/Patio-Curtains-270x270-1.jpg",
    "/images/patio-curtains/Patio-Shade-2.jpg",
    "/images/patio-curtains/Patio-Shade-3.jpg",
    "/images/patio-curtains/z-dolce-vida.jpg"
  ],
  "process": [],
  "retractable-awnings": [
    "/images/retractable-awnings/12100-Retractable-Patio-Awnings-Elite.jpg"
  ],
  "shade-sails": [
    "/images/shade-sails/outdoor-canopies.jpg"
  ],
  "shade-structures": [
    "/images/shade-structures/Shade-Structures-1.jpg",
    "/images/shade-structures/Shade-Structures-2.jpg",
    "/images/shade-structures/Shade-Structures-3.jpg",
    "/images/shade-structures/Shade-Structures-4.jpg",
    "/images/shade-structures/Shade-Structures-5.jpg"
  ],
  "walkway-covers": []
} as const;

export type ImageCategory = keyof typeof IMAGES;

export function getImages(category: string): readonly string[] {
  return (IMAGES as Record<string, readonly string[]>)[category] ?? [];
}
