// AUTO-GENERATED by scripts/build-image-manifest.mjs — do not edit by hand.
// Re-run the script whenever files in public/images/ change.

export const IMAGES = {
  "brand-partners": [],
  "canopies": [
    "/images/canopies/commercial-canopy-01.jpg",
    "/images/canopies/commercial-canopy-02.jpg",
    "/images/canopies/outdoor-dining-canopy-houston-01.jpg",
    "/images/canopies/outdoor-dining-canopy-houston-02.jpg"
  ],
  "carports": [
    "/images/carports/CARPORTS-1-1.jpg",
    "/images/carports/CARPORTS-1-scaled.jpg",
    "/images/carports/CARPORTS-2-scaled.jpg",
    "/images/carports/CARPORTS-3.jpg",
    "/images/carports/CARPORTS-4.jpg",
    "/images/carports/CARPORTS-5-scaled.jpg"
  ],
  "extruded-aluminum": [
    "/images/extruded-aluminum/extruded-aluminum-canopy-03.jpg",
    "/images/extruded-aluminum/extruded-aluminum-canopy-04.jpg",
    "/images/extruded-aluminum/extruded-aluminum-canopy-05.jpg",
    "/images/extruded-aluminum/extruded-aluminum-canopy-06.jpg",
    "/images/extruded-aluminum/extruded-aluminum-canopy-07.jpg",
    "/images/extruded-aluminum/extruded-aluminum-canopy-with-louvers.jpg",
    "/images/extruded-aluminum/extruded-aluminum-walkway-cover-01.jpg",
    "/images/extruded-aluminum/extruded-aluminum-walkway-cover-02.jpg",
    "/images/extruded-aluminum/roll-form-canopy-commercial.jpg"
  ],
  "fabric-awnings": [
    "/images/fabric-awnings/Fabric-awnings-10.jpg",
    "/images/fabric-awnings/Fabric-awnings-2.jpg",
    "/images/fabric-awnings/Fabric-awnings-3.jpg",
    "/images/fabric-awnings/Fabric-awnings-4.jpg",
    "/images/fabric-awnings/Fabric-awnings-5.jpg",
    "/images/fabric-awnings/Fabric-awnings-6.jpg",
    "/images/fabric-awnings/Fabric-awnings-7.jpg",
    "/images/fabric-awnings/Fabric-awnings-8.jpg",
    "/images/fabric-awnings/Fabric-awnings-9.jpg",
    "/images/fabric-awnings/fabric-awning-residential-11.jpg"
  ],
  "gallery": [],
  "gazebos-cabanas": [
    "/images/gazebos-cabanas/gazebo-cabana-backyard-01.jpg",
    "/images/gazebos-cabanas/gazebo-cabana-backyard-02.jpg",
    "/images/gazebos-cabanas/gazebo-cabana-backyard-03.jpg",
    "/images/gazebos-cabanas/gazebo-cabana-blue-dining-shelter.jpg",
    "/images/gazebos-cabanas/gazebo-cabana-outdoor-dining-05.jpg",
    "/images/gazebos-cabanas/gazebo-cabana-outdoor-dining-06.jpg",
    "/images/gazebos-cabanas/gazebo-cabana-poolside-04.jpg",
    "/images/gazebos-cabanas/gazebos-2.png"
  ],
  "hero": [
    "/images/hero/aaa-awning-texas-projects-hero.mp4"
  ],
  "locations": [],
  "logo": [
    "/images/logo/aaa-awning-co-inc.png"
  ],
  "metal-awnings": [
    "/images/metal-awnings/metal-awning-1.jpg",
    "/images/metal-awnings/metal-awning-10.jpg",
    "/images/metal-awnings/metal-awning-2.jpg",
    "/images/metal-awnings/metal-awning-3-scaled.jpg",
    "/images/metal-awnings/metal-awning-4.jpg",
    "/images/metal-awnings/metal-awning-5-scaled.jpg",
    "/images/metal-awnings/metal-awning-6-scaled.jpg",
    "/images/metal-awnings/metal-awning-7.jpg",
    "/images/metal-awnings/metal-awning-8.jpg",
    "/images/metal-awnings/metal-awning-9.jpg",
    "/images/metal-awnings/metal-awning-panel-01.jpg",
    "/images/metal-awnings/metal-awning-panel-03.jpg",
    "/images/metal-awnings/metal-awning-panel-04.jpg",
    "/images/metal-awnings/metal-awning-panel-05.jpg"
  ],
  "motorized-screens": [],
  "patio-curtains": [
    "/images/patio-curtains/Curtains-1.jpg",
    "/images/patio-curtains/Curtains-2-scaled.jpg",
    "/images/patio-curtains/Curtains-3-scaled-e1619539405515.jpg",
    "/images/patio-curtains/Curtains-4.jpg",
    "/images/patio-curtains/Curtains-5.jpg",
    "/images/patio-curtains/Curtains-6.jpg",
    "/images/patio-curtains/patio-curtain-installation.jpg",
    "/images/patio-curtains/patio-curtain-residential-dolce-vida.jpg",
    "/images/patio-curtains/patio-curtain-shade-02.jpg",
    "/images/patio-curtains/patio-curtain-shade-03.jpg"
  ],
  "process": [],
  "retractable-awnings": [
    "/images/retractable-awnings/retractable-patio-awning-elite.jpg"
  ],
  "shade-sails": [
    "/images/shade-sails/shade-sail-residential-01.jpg"
  ],
  "shade-structures": [
    "/images/shade-structures/Shade-Structures-1.jpg",
    "/images/shade-structures/Shade-Structures-2.jpg",
    "/images/shade-structures/Shade-Structures-3.jpg",
    "/images/shade-structures/Shade-Structures-4.jpg",
    "/images/shade-structures/Shade-Structures-5.jpg"
  ],
  "walkway-covers": []
} as const;

export type ImageCategory = keyof typeof IMAGES;

export function getImages(category: string): readonly string[] {
  return (IMAGES as Record<string, readonly string[]>)[category] ?? [];
}
